name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build PR code
        run: npm run build

      - name: Deploy docs
        run: cd docs && npm install && npm run deploy
        env:
          GIT_USER: Walrussuit101
          GIT_PASS: ${{ secrets.GIT_TOKEN }}
