name: test-on-pr

on:
  pull_request:
    types: [opened, synchronize]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Test PR code
        run: npm test
